version: '3.8'

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_LOCAL_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=docker
      - JWT_ACCESS_KEY=qofdjeifhuhbjasjigudsfdsfsd
      - JWT_REFRESH_KEY=qo231edqwdjeidafdsfergegbeh
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - 5436:5432
